using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace EditorTools.Generators
{
    public static class PathsGenerator
    {
        private const string SCRIPT_PATH = "Assets/_Main/Scripts/Constant/Paths.cs";
        
        [MenuItem("Tools/Regenerate Resources Paths")]
        public static void Generate()
        {
            var guids = AssetDatabase.FindAssets("", new[] { "Assets/_Main/Resources" });
            
            var fullPaths = new List<string>();
            foreach (var guid in guids)
            {
                var path = AssetDatabase.GUIDToAssetPath(guid);
                var type = AssetDatabase.GetMainAssetTypeAtPath(path);
                if (typeof(GameObject).IsAssignableFrom(type) ||
                    typeof(ScriptableObject).IsAssignableFrom(type))
                { fullPaths.Add(path); }
            }
            
            var paths = fullPaths.Select(Tools.PathHelper.AssetPathToResourcePath).ToList();
            
            var names = new List<string>();
            foreach (var path in paths)
            {
                var name = path.Split('/').Last();
                if (path.Contains("Prefab")) name += "Prefab";
                else if (path.Contains("Config") || path.Contains("Template"))
                { name = name.Replace("_", ""); }

                name += "Path";
                names.Add(name);
            }

            var entries = new List<string>();
            for (var i = 0; i < paths.Count; i++)
            {
                var name = names[i];
                var entry = $"        public static string {name} => \"{paths[i]}\";";
                entries.Add(entry);
            }
            
            var sb = new StringBuilder();

            sb.AppendLine("//AUTOGENERATED//");
            
            sb.AppendLine("using System.IO;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("");

            sb.AppendLine("namespace Constant");
            sb.AppendLine("{");
            
            sb.AppendLine("    public static class Paths");
            sb.AppendLine("    {");

            sb.AppendLine("        public static string SaveFilePath => Path.Combine(Application.persistentDataPath, \"save.json\");");
            sb.AppendLine("");
            
            foreach (var entry in entries) sb.AppendLine(entry);
            sb.AppendLine("    }");
            sb.AppendLine("}");
            
            File.WriteAllText(SCRIPT_PATH, sb.ToString());
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
        }
    }
}