using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;

namespace EditorTools.Generators
{
    public static class ResourceServiceGenerator
    {
        private const string SCRIPT_PATH = "Assets/_Main/Scripts/Global/R.cs";

        [MenuItem("Tools/Regenerate Resources Links")]
        public static void Generate()
        {
            var configEntries = CollectConfigEntries();
            var prefabEntries = CollectPrefabEntries();
            var templatesEntries = CollectTemplatesEntries();
            var systemsEntries = CollectSystemsEntries();
            
            var sb = new StringBuilder();

            sb.AppendLine("//AUTOGENERATED//");
            sb.AppendLine("");
            sb.AppendLine("using Config;");
            sb.AppendLine("using Template;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using EntitySystem;");
            sb.AppendLine("");
            sb.AppendLine("public static class R");
            sb.AppendLine("{");
            sb.AppendLine("    public static T Get<T>(string path) where T : Object => Resources.Load<T>(path);");
            sb.AppendLine("    public static T[] GetAll<T>(string folder) where T : Object => Resources.LoadAll<T>(folder);");
            sb.AppendLine("    public static ResourceRequest GetAsync<T>(string path) where T : Object => Resources.LoadAsync<T>(path);");
            sb.AppendLine("");

            foreach (var configEntry in configEntries) sb.AppendLine(configEntry);
            sb.AppendLine("");
            
            foreach (var prefabEntry in prefabEntries) sb.AppendLine(prefabEntry);
            sb.AppendLine("");
            
            foreach (var templateEntry in templatesEntries) sb.AppendLine(templateEntry);
            sb.AppendLine("");

            foreach (var systemsEntry in systemsEntries) sb.AppendLine(systemsEntry);
            sb.AppendLine("");
            
            sb.AppendLine("}");
            
            File.WriteAllText(SCRIPT_PATH, sb.ToString());
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
        }

        private static List<string> CollectSystemsEntries()
        {
            var guids = AssetDatabase.FindAssets("System", new []{ "Assets/_Main/Resources/System" });
            var (paths, names) = GetPathsAndNames(guids);
            
            var types = GetTypesFromNames(names);
            
            var entries = new List<string>();
            for (var i = 0; i < guids.Length; i++)
            {
                var type = types[i];
                var name = names[i].Replace("_", "");
                var path = paths[i];
                entries.Add($"    public static {type} {name} => Resources.Load<{type}>(\"{path}\");");
            }
            return entries;
        }

        private static List<string> CollectTemplatesEntries()
        {
            var guids = AssetDatabase.FindAssets("Template", new []{ "Assets/_Main/Resources/Template" });
            var (paths, names) = GetPathsAndNames(guids);
            
            var types = GetTypesFromNames(names);

            var entries = new List<string>();
            for (var i = 0; i < guids.Length; i++)
            {
                var type = types[i];
                var name = names[i].Replace("_", "");
                var path = paths[i];
                entries.Add($"    public static {type} {name} => Resources.Load<{type}>(\"{path}\");");
            }
            return entries;
        }

        private static List<string> CollectPrefabEntries()
        {
            var guids = AssetDatabase.FindAssets("t:Prefab", new []{ "Assets/_Main/Resources/Prefab" });
            var (paths, names) = GetPathsAndNames(guids);
            
            var entries = new List<string>();
            for (var i = 0; i < guids.Length; i++)
            {
                const string type = "GameObject";
                var name = names[i] + "Prefab";
                var path = paths[i];
                entries.Add($"    public static {type} {name} => Resources.Load<{type}>(\"{path}\");");
            }
            
            return entries;
        }
        
        private static List<string> CollectConfigEntries()
        {
            var guids = AssetDatabase.FindAssets("Config", new []{ "Assets/_Main/Resources/Config" });
            var (paths, names) = GetPathsAndNames(guids);
            
            var types = GetTypesFromNames(names);

            var entries = new List<string>();
            for (var i = 0; i < guids.Length; i++)
            {
                var type = types[i];
                var name = names[i].Replace("_", "");
                var path = paths[i];
                entries.Add($"    public static {type} {name} => Resources.Load<{type}>(\"{path}\");");
            }
            return entries;
        }

        private static (List<string> paths, List<string> names) GetPathsAndNames(string[] guids)
        {
            var fullPaths = guids.Select(AssetDatabase.GUIDToAssetPath);
            var paths = fullPaths.Select(Tools.PathHelper.AssetPathToResourcePath).ToList();
            var names = paths.Select(path => path.Split('/').Last()).ToList();
            
            return (paths, names);
        }

        private static List<string> GetTypesFromNames(List<string> names)
        {
            var types = new List<string>();
            foreach (var name in names)
            {
                var type = name;
                if (name.Contains('_'))
                { type = name.Split('_')[0]; }
                types.Add(type);
            }
            
            return types;
        }
    }
}