//AUTOGENERATED//
using System.IO;
using UnityEngine;

namespace Constant
{
    public static class Paths
    {
        public static string SaveFilePath => Path.Combine(Application.persistentDataPath, "save.json");

        public static string CameraConfigDefaultPath => "Config/Cameras/CameraConfig_Default";
        public static string PlayerConfigPath => "Config/Player/PlayerConfig";
        public static string AppConfigPath => "Config/Preferences/AppConfig";
        public static string SceneConfigMenuPath => "Config/Scenes/SceneConfig_Menu";
        public static string SceneConfigShelterPath => "Config/Scenes/SceneConfig_Shelter";
        public static string GameScreenPrefabPath => "Prefab/UI/GameScreen";
        public static string LoadingScreenPrefabPath => "Prefab/UI/LoadingScreen";
        public static string MainMenuPrefabPath => "Prefab/UI/MainMenu";
        public static string UIRootPrefabPath => "Prefab/UI/UIRoot";
        public static string DefaultCameraPrefabPath => "Prefab/World/Camera/DefaultCamera";
        public static string DummyPrefabPath => "Prefab/World/Entity/Dummy";
        public static string MovementSystemPath => "System/MovementSystem";
        public static string EntityTemplateDummyPath => "Template/Entity/EntityTemplate_Dummy";
    }
}
