//AUTOGENERATED//

using Config;
using Template;
using UnityEngine;
using EntitySystem;

public static class R
{
    public static T Get<T>(string path) where T : Object => Resources.Load<T>(path);
    public static T[] GetAll<T>(string folder) where T : Object => Resources.LoadAll<T>(folder);
    public static ResourceRequest GetAsync<T>(string path) where T : Object => Resources.LoadAsync<T>(path);

    public static CameraConfig CameraConfigDefault => Resources.Load<CameraConfig>("Config/Cameras/CameraConfig_Default");
    public static PlayerConfig PlayerConfig => Resources.Load<PlayerConfig>("Config/Player/PlayerConfig");
    public static AppConfig AppConfig => Resources.Load<AppConfig>("Config/Preferences/AppConfig");
    public static GameConfig GameConfig => Resources.Load<GameConfig>("Config/Preferences/GameConfig");
    public static SceneConfig SceneConfigMenu => Resources.Load<SceneConfig>("Config/Scenes/SceneConfig_Menu");
    public static SceneConfig SceneConfigShelter => Resources.Load<SceneConfig>("Config/Scenes/SceneConfig_Shelter");

    public static GameObject GameScreenPrefab => Resources.Load<GameObject>("Prefab/UI/GameScreen");
    public static GameObject LoadingScreenPrefab => Resources.Load<GameObject>("Prefab/UI/LoadingScreen");
    public static GameObject MainMenuPrefab => Resources.Load<GameObject>("Prefab/UI/MainMenu");
    public static GameObject UIRootPrefab => Resources.Load<GameObject>("Prefab/UI/UIRoot");
    public static GameObject DefaultCameraPrefab => Resources.Load<GameObject>("Prefab/World/Camera/DefaultCamera");
    public static GameObject DummyPrefab => Resources.Load<GameObject>("Prefab/World/Entity/Dummy");

    public static EntityTemplate EntityTemplateDummy => Resources.Load<EntityTemplate>("Template/Entity/EntityTemplate_Dummy");

    public static MovementSystem MovementSystem => Resources.Load<MovementSystem>("System/MovementSystem");
    public static PlayerControllerSystem PlayerControllerSystem => Resources.Load<PlayerControllerSystem>("System/PlayerControllerSystem");

}
