using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;

namespace EditorTools
{
    public static class SceneNamesGenerator
    {
        private const string STAGE_NAMES_PATH = "Assets/_Main/Scripts/Constant/SceneNames.cs";

        [MenuItem("Tools/Generate Scene Names")]
        public static void Generate()
        {
            var scenesGuids = AssetDatabase.FindAssets("t:Scene", new[] { "Assets/_Main/Scenes" });
            var scenes = new string[scenesGuids.Length];
            for (var guidIndex = 0; guidIndex < scenesGuids.Length; guidIndex++)
            {
                var sceneAssetPath = AssetDatabase.GUIDToAssetPath(scenesGuids[guidIndex]);
                var sceneAssetName = Path.GetFileNameWithoutExtension(sceneAssetPath);
                scenes[guidIndex] = sceneAssetName;
            }

            GenerateEnum(STAGE_NAMES_PATH, "SceneNames", scenes.ToList());
        }

        private static void GenerateEnum(string path, string enumName, List<string> elements)
        {
            var sb = new StringBuilder();
            
            sb.AppendLine("// AUTOGENERATED //");
            sb.AppendLine("");
            
            sb.AppendLine("namespace Constant");
            sb.AppendLine("{");

            sb.AppendLine($"    public enum {enumName}");
            sb.AppendLine("    {");
            
            foreach (var element in elements)
            {sb.AppendLine($"        {element},");}
            
            sb.AppendLine("    }");
            sb.AppendLine("}");
            
            File.WriteAllText(path, sb.ToString());
            
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
        }
    }
}